// GENERATED FILE — do not edit by hand.
// Run `pnpm gen:capabilities` to refresh. Derived by walking the import
// graph (see tool-capabilities.derive.ts): a tool needs AI if it can reach
// a module that reads a provider key, and uses a browser if it can reach
// the Chromium pool. tool-capabilities.test.ts fails when this drifts.
//
// 96 tools · 38 need AI · 15 use a browser.

export const TOOL_CAPABILITIES = [
  { slug: "ads-funnel", needsAI: true, usesBrowser: false },
  { slug: "ai-citation-tactics", needsAI: false, usesBrowser: false },
  { slug: "ai-overview", needsAI: true, usesBrowser: false },
  { slug: "ai-robots", needsAI: false, usesBrowser: false },
  { slug: "ai-schema", needsAI: true, usesBrowser: false },
  { slug: "ai-slop", needsAI: false, usesBrowser: false },
  { slug: "aio-passage", needsAI: true, usesBrowser: false },
  { slug: "anchor-distribution", needsAI: false, usesBrowser: false },
  { slug: "attack-briefs", needsAI: true, usesBrowser: true },
  { slug: "auto-link", needsAI: true, usesBrowser: false },
  { slug: "backlink-discovery", needsAI: false, usesBrowser: false },
  { slug: "bing", needsAI: false, usesBrowser: false },
  { slug: "branded-split", needsAI: false, usesBrowser: false },
  { slug: "brief", needsAI: true, usesBrowser: true },
  { slug: "browser-agent", needsAI: true, usesBrowser: true },
  { slug: "bulk-alt", needsAI: true, usesBrowser: false },
  { slug: "bulk-scan", needsAI: false, usesBrowser: true },
  { slug: "cannibalization", needsAI: false, usesBrowser: false },
  { slug: "canonical-audit", needsAI: false, usesBrowser: false },
  { slug: "cluster", needsAI: true, usesBrowser: true },
  { slug: "code-generator", needsAI: true, usesBrowser: false },
  { slug: "content-attack-brief", needsAI: true, usesBrowser: false },
  { slug: "content-grader", needsAI: false, usesBrowser: true },
  { slug: "content-helpers", needsAI: true, usesBrowser: false },
  { slug: "content-score", needsAI: true, usesBrowser: false },
  { slug: "crux", needsAI: false, usesBrowser: false },
  { slug: "crux-origin", needsAI: false, usesBrowser: false },
  { slug: "disavow", needsAI: false, usesBrowser: false },
  { slug: "dns-whois", needsAI: false, usesBrowser: false },
  { slug: "domain-overview", needsAI: false, usesBrowser: false },
  { slug: "eeat-audit", needsAI: true, usesBrowser: false },
  { slug: "expert-panel", needsAI: true, usesBrowser: false },
  { slug: "external", needsAI: false, usesBrowser: false },
  { slug: "facet-trap", needsAI: false, usesBrowser: false },
  { slug: "freshness", needsAI: false, usesBrowser: false },
  { slug: "gbp-reply", needsAI: true, usesBrowser: false },
  { slug: "geo-score", needsAI: true, usesBrowser: false },
  { slug: "geo-swot", needsAI: true, usesBrowser: true },
  { slug: "github-pr", needsAI: false, usesBrowser: false },
  { slug: "gsc-coverage", needsAI: true, usesBrowser: false },
  { slug: "headers", needsAI: false, usesBrowser: false },
  { slug: "health-check", needsAI: false, usesBrowser: true },
  { slug: "hreflang", needsAI: false, usesBrowser: false },
  { slug: "hreflang-gen", needsAI: false, usesBrowser: false },
  { slug: "image-gen", needsAI: true, usesBrowser: false },
  { slug: "indexnow", needsAI: false, usesBrowser: false },
  { slug: "intent-classifier", needsAI: true, usesBrowser: false },
  { slug: "internal-linking", needsAI: false, usesBrowser: false },
  { slug: "keyword-difficulty", needsAI: true, usesBrowser: true },
  { slug: "link-checker", needsAI: false, usesBrowser: false },
  { slug: "link-graph", needsAI: false, usesBrowser: false },
  { slug: "link-recommender", needsAI: true, usesBrowser: false },
  { slug: "llms-txt", needsAI: true, usesBrowser: false },
  { slug: "local-cwv", needsAI: false, usesBrowser: true },
  { slug: "meta-tag-generator", needsAI: true, usesBrowser: false },
  { slug: "migration-map", needsAI: false, usesBrowser: false },
  { slug: "migration-parity", needsAI: false, usesBrowser: false },
  { slug: "mobile-friendly", needsAI: false, usesBrowser: false },
  { slug: "news-headline", needsAI: true, usesBrowser: false },
  { slug: "og-image", needsAI: false, usesBrowser: false },
  { slug: "outreach-personalize", needsAI: true, usesBrowser: false },
  { slug: "pagerank", needsAI: false, usesBrowser: false },
  { slug: "perf-budget", needsAI: false, usesBrowser: false },
  { slug: "person-schema", needsAI: false, usesBrowser: false },
  { slug: "pixel-preview", needsAI: false, usesBrowser: false },
  { slug: "plagiarism", needsAI: true, usesBrowser: false },
  { slug: "programmatic-seo", needsAI: false, usesBrowser: false },
  { slug: "rank-where", needsAI: false, usesBrowser: true },
  { slug: "reddit-research", needsAI: false, usesBrowser: false },
  { slug: "redirects-bulk", needsAI: false, usesBrowser: false },
  { slug: "redirects-manager", needsAI: false, usesBrowser: false },
  { slug: "refresh", needsAI: true, usesBrowser: true },
  { slug: "render", needsAI: false, usesBrowser: true },
  { slug: "reputation-abuse-risk", needsAI: true, usesBrowser: false },
  { slug: "robots", needsAI: false, usesBrowser: false },
  { slug: "robots-history", needsAI: false, usesBrowser: false },
  { slug: "schema", needsAI: true, usesBrowser: false },
  { slug: "schema-validate", needsAI: false, usesBrowser: false },
  { slug: "screenshot-import", needsAI: true, usesBrowser: false },
  { slug: "search-volume", needsAI: false, usesBrowser: false },
  { slug: "security", needsAI: false, usesBrowser: false },
  { slug: "serp-features", needsAI: false, usesBrowser: true },
  { slug: "serp-volatility", needsAI: false, usesBrowser: false },
  { slug: "sitemap", needsAI: false, usesBrowser: false },
  { slug: "social-preview", needsAI: false, usesBrowser: false },
  { slug: "soft-404", needsAI: false, usesBrowser: false },
  { slug: "summarizer", needsAI: true, usesBrowser: false },
  { slug: "sxo", needsAI: true, usesBrowser: false },
  { slug: "traffic-drop", needsAI: true, usesBrowser: false },
  { slug: "trending", needsAI: true, usesBrowser: true },
  { slug: "uptime", needsAI: false, usesBrowser: false },
  { slug: "utm-attribution", needsAI: false, usesBrowser: false },
  { slug: "wayback", needsAI: false, usesBrowser: false },
  { slug: "wp-hack-scan", needsAI: false, usesBrowser: false },
  { slug: "youtube", needsAI: false, usesBrowser: false },
  { slug: "youtube-audit", needsAI: true, usesBrowser: false },
] as const;
