/**
 * Where a number came from, said out loud.
 *
 * The standing rule from the August audit is that a number shown to a
 * user needs provenance: where it came from, how fresh, how confident.
 * That rule got applied to AI-visibility rows and then to rankings, and
 * nowhere else — so a health score derived from our own crawler, a
 * traffic figure straight from Google, and an estimate we computed from
 * a heuristic all rendered as the same confident bold number.
 *
 * They are not the same. An agency puts these in a client report, and
 * the difference between "Google says 4,182 clicks" and "we estimate
 * roughly 4,000 sessions" is the difference between a defensible claim
 * and one that falls apart when the client checks.
 *
 * This is the shared vocabulary. One place, so the labels can't drift —
 * CLAUDE.md's fourth standing rule is never to add a second hardcoded
 * list of something that already exists, and every such pair in this
 * codebase had already drifted by the time it was found.
 */

import {
  Bot,
  Calculator,
  Database,
  Gauge,
  Globe,
  PenLine,
  Radar,
} from "lucide-react";
import type { LucideIcon } from "lucide-react";

export type DataSource =
  /** Google Search Console. Google's own numbers about your site. */
  | "gsc"
  /** Google Analytics 4. */
  | "ga4"
  /** Our own crawler visiting the site. */
  | "crawl"
  /** PageSpeed Insights / CrUX — real-world Chrome data. */
  | "psi"
  /** A scraped search results page. */
  | "scrape"
  /** Generated by a language model. */
  | "ai"
  /** Typed in by the user. */
  | "manual"
  /** Derived by us from other numbers, with assumptions. */
  | "estimate";

type Meta = {
  label: string;
  icon: LucideIcon;
  /** Sentence shown on hover. Says what the number IS, and its limits. */
  detail: string;
  tone: string;
};

const META: Record<DataSource, Meta> = {
  gsc: {
    label: "Search Console",
    icon: Database,
    detail:
      "Google's own figures for your site. As authoritative as this gets — but Search Console lags two to three days, and it only knows queries you actually appeared for.",
    tone: "bg-emerald-500/10 text-emerald-300 ring-emerald-500/25",
  },
  ga4: {
    label: "Analytics",
    icon: Gauge,
    detail:
      "From Google Analytics 4. Reflects visitors who weren't blocked by an ad blocker or consent banner, so it under-counts to some degree on every site.",
    tone: "bg-emerald-500/10 text-emerald-300 ring-emerald-500/25",
  },
  crawl: {
    label: "Our crawl",
    icon: Radar,
    detail:
      "Measured by this tool visiting the pages itself. Accurate about what was on the page when we looked, which may not be what Google last saw.",
    tone: "bg-cyan-500/10 text-cyan-300 ring-cyan-500/25",
  },
  psi: {
    label: "PageSpeed",
    icon: Gauge,
    detail:
      "From Google's PageSpeed Insights. Field data comes from real Chrome users over the last 28 days; lab data is one simulated load and can differ.",
    tone: "bg-cyan-500/10 text-cyan-300 ring-cyan-500/25",
  },
  scrape: {
    label: "Live check",
    icon: Globe,
    detail:
      "Read from a live search results page. Current, but it's what one server was shown rather than what your visitors see — expect a position or two of noise from personalisation.",
    tone: "bg-white/5 text-muted-foreground ring-white/10",
  },
  ai: {
    label: "AI-written",
    icon: Bot,
    detail:
      "Written by a language model from your data. Worth reading before it goes to a client — models are fluent about things they've got wrong.",
    tone: "bg-violet-500/10 text-violet-300 ring-violet-500/25",
  },
  manual: {
    label: "Entered by you",
    icon: PenLine,
    detail: "Typed in by hand. This tool hasn't verified it.",
    tone: "bg-white/5 text-muted-foreground ring-white/10",
  },
  estimate: {
    label: "Estimate",
    icon: Calculator,
    detail:
      "Worked out from other numbers using assumptions, not measured. Fine for prioritising; don't put it in a client report as fact.",
    tone: "bg-amber-500/10 text-amber-300 ring-amber-500/25",
  },
};

export function DataSourceBadge({
  source,
  /** ISO date or date the figure DESCRIBES — not when it was fetched. */
  asOf,
  /** Extra context appended to the tooltip, e.g. "across 1,204 impressions". */
  note,
  className,
}: {
  source: DataSource | null | undefined;
  asOf?: string | Date | null;
  note?: string;
  className?: string;
}) {
  if (!source) return null;
  const meta = META[source];
  if (!meta) return null;
  const Icon = meta.icon;

  const asOfLabel = asOf
    ? typeof asOf === "string"
      ? asOf.slice(0, 10)
      : asOf.toISOString().slice(0, 10)
    : null;

  return (
    <span
      title={[meta.detail, note, asOfLabel ? `Figures for ${asOfLabel}.` : null]
        .filter(Boolean)
        .join(" ")}
      className={`inline-flex items-center gap-1 rounded-full px-1.5 py-0.5 text-[10px] font-medium ring-1 ring-inset ${meta.tone} ${className ?? ""}`}
    >
      <Icon className="size-2.5" />
      {meta.label}
      {asOfLabel && <span className="opacity-70">· {asOfLabel}</span>}
    </span>
  );
}

/** The label alone, for places too tight for a badge. */
export function dataSourceLabel(source: DataSource): string {
  return META[source]?.label ?? source;
}

export function dataSourceDetail(source: DataSource): string {
  return META[source]?.detail ?? "";
}

export const DATA_SOURCES = Object.keys(META) as DataSource[];
